version: '3.1'
services:
  backend__test:
    build:
      dockerfile: Dockerfile
      context: ./backend/source
    ports:
      - "8002:8002"
    volumes:
      - ./backend/source:/usr/src/app
    environment:
      - environment=prod-api
      - db_connection_url=mongodb+srv://website_live:1mR6FOKNXrCcVtoP@cluster0.sngd13i.mongodb.net/?retryWrites=true&w=majority
      - cors_allowed=["*"]
      - database_name=mvp2
      - unique_collection=unique_supplier_lookup
      - profit_collection=profit_supplier_lookup
      - username=Martine
      - email=martine@gmail.com
      - password=changeme
      - JWT_SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload

  frontend_test:
    image: nginx:1-alpine
    ports:
      - 8003:80
    volumes:
      - ./frontend/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
