version: '3.1'
services:
  backend_prod:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MONGO_USER=website_live
      - MONGO_PASS=1mR6FOKNXrCcVtoP
      - environment=prod-api
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend_prod:
    image: nginx:1-alpine
    ports:
      - 8001:80
    volumes:
      - ./frontend/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
