version: '3.1'
services:
  clickbuy:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MONGO_USER=fiverr_user
      - MONGO_PASS=fiverr_user
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    # depends_on:
    #   - mongodb
    networks:
      - my-network

  # mongodb:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./mongodb/db:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: supersecret
  #   networks:
  #     - my-network

  # my-redis:
  #   image: redis:latest
  #   volumes:
  #     - ./myredis/conf:/data
  #   ports:
  #     - 6378:6379
  #   networks:
  #     - my-network


networks:
  my-network:
    driver: bridge
