version: '3.1'
services:
  backend__prod:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MONGO_USER=website_live
      - MONGO_PASS=1mR6FOKNXrCcVtoP
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

  frontend_prod:
    image: nginx:1-alpine
    ports:
      - 8081:80
    volumes:
      - ./frontend/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
