version: '3.1'
services:
  backend__test:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MONGO_USER=website_live
      - MONGO_PASS=1mR6FOKNXrCcVtoP
      - environment=test-api
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload

  frontend_test:
    image: nginx:1-alpine
    ports:
      - 8003:80
    volumes:
      - ./frontend/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
