version: '3.1'
services:
  clickbuy:
    build:
      dockerfile: Dockerfile
      context: ./fastapi-clickbuy
    ports:
      - "8080:8080"
    volumes:
      - ./fastapi-clickbuy:/usr/src/app
    environment:
      - MONGO_USER=fiverr_user
      - MONGO_PASS=fiverr_user
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: supersecret
    networks:
      - my-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: supersecret
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
